version: "3.4"

services:
  local:
    stdin_open: true
    tty: true
    image: dleongsh/esc-service:v1.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./:/workspace
      - /mnt/d/datasets/fleurs_ms_test:/dataset
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
